docker:
  image: "maven:3.5.0-jdk-8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
merge:
  script: mvn clean install
release:
  script: |
    mvn versions:set "-DnewVersion=${tag}"
    cd atom-starter
    mvn versions:set "-DnewVersion=${tag}"
    mvn versions:set-property -Dproperty=atom.version "-DnewVersion=${tag}"
    cd -
    git commit -am "[release] oo-atom-${tag}"
    mvn clean deploy -Poo-atom --settings /home/r/settings.xml
